# Generated by Django 4.0.5 on 2022-08-22 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Static_ID', models.CharField(choices=[('https://www.github.com', 'https://www.github.com'), ('https://www.geeksforgeeks.org', 'https://www.geeksforgeeks.org'), ('https://www.tutorialspoint.com', 'https://www.tutorialspoint.com')], max_length=100)),
                ('Dynamic_ID', models.CharField(max_length=500)),
            ],
        ),
    ]
